# Generated by Django 5.0 on 2023-12-14 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('category', models.CharField(choices=[('Fresh Meat', 'Fresh Meat'), ('Vegetables', 'Vegetables'), ('Fruit & Nut Gifts', 'Fruit & Nut Gifts'), ('Fresh Berries', 'Fresh Berries'), ('Ocean Foods', 'Ocean Foods'), ('Butter and eggs', 'Butter and eggs'), ('Fastfood', 'Fastfood'), ('Fresh Onion', 'Fresh Onion'), ('Papayaya & Crisps', 'Papayaya & Crisps'), ('Oatmeal', 'Oatmeal'), ('Fresh Banana', 'Fresh Banana')], max_length=20)),
                ('color', models.CharField(blank=True, choices=[('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('Gray', 'Gray'), ('Green', 'Green')], max_length=8, null=True)),
                ('size', models.CharField(blank=True, choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Tiny', 'Tiny')], max_length=8, null=True)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('discription', models.TextField()),
                ('information', models.TextField()),
                ('reviews', models.TextField(blank=True, null=True)),
                ('p_image', models.ImageField(upload_to='Product_Image')),
                ('p_image1', models.ImageField(null=True, upload_to='Product_Image1')),
                ('p_image2', models.ImageField(null=True, upload_to='Product_Image2')),
                ('p_image3', models.ImageField(null=True, upload_to='Product_Image3')),
                ('p_image4', models.ImageField(null=True, upload_to='Product_Image4')),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Stock Out', 'Stock Out')], max_length=20)),
                ('shipping', models.CharField(max_length=100)),
                ('weight', models.CharField(choices=[('0.5kg', '0.5kg'), ('1-KG', 'Per KG'), ('500ml', '500ml'), ('1 Box', 'Per Box'), ('Per Piece', 'Per Piece '), ('1 Litre', 'Per Litre')], max_length=15)),
                ('sale_off_discount_parcent', models.FloatField(blank=True, null=True)),
                ('latest_products', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Chattogram', 'Chattogram'), ('Mymenshing', 'Mymenshing'), ('Sylhet', 'Sylhet')], max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=150)),
                ('mobile', models.CharField(default='+880 ', max_length=15)),
                ('effective_delivery', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=70)),
                ('customar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
