# Generated by Django 4.2.5 on 2023-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_carousel_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_slider',
            name='image',
            field=models.ImageField(null=True, upload_to='carousel'),
        ),
    ]
